; <?php exit; ?> DO NOT REMOVE THIS LINE
; file automatically generated or modified by Matomo; you can manually override the default values in global.ini.php by redefining them in this file.
[database]
host = "localhost"
username = "root"
password = "chaoban"
dbname = "analytics"
tables_prefix = "mt_"

[database_reader]
host = "localhost"
username = "root"
password = "chaoban"
dbname = "analytics"

[General]
release_channel = "latest_3x_stable"
force_ssl = 0
enable_plugin_upload = 1
salt = "f90344717881471acdf1ddcccf417935"
trusted_hosts[] = ""
cors_domains[] = "*"

[Plugins]
Plugins[] = "CorePluginsAdmin"
Plugins[] = "CoreAdminHome"
Plugins[] = "CoreHome"
Plugins[] = "WebsiteMeasurable"
Plugins[] = "IntranetMeasurable"
Plugins[] = "Diagnostics"
Plugins[] = "CoreVisualizations"
Plugins[] = "Proxy"
Plugins[] = "API"
Plugins[] = "Widgetize"
Plugins[] = "Transitions"
Plugins[] = "LanguagesManager"
Plugins[] = "Actions"
Plugins[] = "Dashboard"
Plugins[] = "MultiSites"
Plugins[] = "Referrers"
Plugins[] = "UserLanguage"
Plugins[] = "DevicesDetection"
Plugins[] = "Goals"
Plugins[] = "Ecommerce"
Plugins[] = "SEO"
Plugins[] = "Events"
Plugins[] = "UserCountry"
Plugins[] = "GeoIp2"
Plugins[] = "VisitsSummary"
Plugins[] = "VisitFrequency"
Plugins[] = "VisitTime"
Plugins[] = "VisitorInterest"
Plugins[] = "RssWidget"
Plugins[] = "Feedback"
Plugins[] = "Monolog"
Plugins[] = "Login"
Plugins[] = "TwoFactorAuth"
Plugins[] = "UsersManager"
Plugins[] = "SitesManager"
Plugins[] = "Installation"
Plugins[] = "CoreUpdater"
Plugins[] = "CoreConsole"
Plugins[] = "ScheduledReports"
Plugins[] = "UserCountryMap"
Plugins[] = "Live"
Plugins[] = "CustomVariables"
Plugins[] = "PrivacyManager"
Plugins[] = "ImageGraph"
Plugins[] = "Annotations"
Plugins[] = "MobileMessaging"
Plugins[] = "Overlay"
Plugins[] = "SegmentEditor"
Plugins[] = "Insights"
Plugins[] = "Morpheus"
Plugins[] = "Contents"
Plugins[] = "BulkTracking"
Plugins[] = "Resolution"
Plugins[] = "DevicePlugins"
Plugins[] = "Heartbeat"
Plugins[] = "Intl"
Plugins[] = "Marketplace"
Plugins[] = "UserId"
Plugins[] = "CustomPiwikJs"
Plugins[] = "Tour"
Plugins[] = "DBStats"
Plugins[] = "Provider"
Plugins[] = "TagManager"
Plugins[] = "AbTesting"
Plugins[] = "ActivityLog"
Plugins[] = "AjaxOptOut"
Plugins[] = "AOM"
Plugins[] = "BotTracker"
Plugins[] = "Cohorts"
Plugins[] = "CustomDimensions"
Plugins[] = "CustomReports"
Plugins[] = "DeviceDetectorCache"
Plugins[] = "DevicePixelRatio"
Plugins[] = "FlagCounter"
Plugins[] = "FormAnalytics"
Plugins[] = "Funnels"
Plugins[] = "GoogleAnalyticsImporter"
Plugins[] = "GoogleTheme"
Plugins[] = "HeatmapSessionRecording"
Plugins[] = "IntranetGeoIP"
Plugins[] = "IP2Location"
Plugins[] = "LogViewer"
Plugins[] = "MarketingCampaignsReporting"
Plugins[] = "MediaAnalytics"
Plugins[] = "MultiChannelConversionAttribution"
Plugins[] = "QueuedTracking"
Plugins[] = "ReferrersManager"
Plugins[] = "RollUpReporting"
Plugins[] = "SearchEngineKeywordsPerformance"
Plugins[] = "SecurityInfo"
Plugins[] = "ShortcodeTracker"
Plugins[] = "SiteUrlTrackingID"
Plugins[] = "TrackingCodeCustomizer"
Plugins[] = "TreemapVisualization"
Plugins[] = "UsersFlow"
Plugins[] = "Webhook"
Plugins[] = "WhiteLabel"

[PluginsInstalled]
PluginsInstalled[] = "Diagnostics"
PluginsInstalled[] = "Login"
PluginsInstalled[] = "CoreAdminHome"
PluginsInstalled[] = "UsersManager"
PluginsInstalled[] = "SitesManager"
PluginsInstalled[] = "Installation"
PluginsInstalled[] = "Monolog"
PluginsInstalled[] = "Intl"
PluginsInstalled[] = "CorePluginsAdmin"
PluginsInstalled[] = "CoreHome"
PluginsInstalled[] = "WebsiteMeasurable"
PluginsInstalled[] = "IntranetMeasurable"
PluginsInstalled[] = "CoreVisualizations"
PluginsInstalled[] = "Proxy"
PluginsInstalled[] = "API"
PluginsInstalled[] = "Widgetize"
PluginsInstalled[] = "Transitions"
PluginsInstalled[] = "LanguagesManager"
PluginsInstalled[] = "Actions"
PluginsInstalled[] = "Dashboard"
PluginsInstalled[] = "MultiSites"
PluginsInstalled[] = "Referrers"
PluginsInstalled[] = "UserLanguage"
PluginsInstalled[] = "DevicesDetection"
PluginsInstalled[] = "Goals"
PluginsInstalled[] = "Ecommerce"
PluginsInstalled[] = "SEO"
PluginsInstalled[] = "Events"
PluginsInstalled[] = "UserCountry"
PluginsInstalled[] = "GeoIp2"
PluginsInstalled[] = "VisitsSummary"
PluginsInstalled[] = "VisitFrequency"
PluginsInstalled[] = "VisitTime"
PluginsInstalled[] = "VisitorInterest"
PluginsInstalled[] = "RssWidget"
PluginsInstalled[] = "Feedback"
PluginsInstalled[] = "TwoFactorAuth"
PluginsInstalled[] = "CoreUpdater"
PluginsInstalled[] = "CoreConsole"
PluginsInstalled[] = "ScheduledReports"
PluginsInstalled[] = "UserCountryMap"
PluginsInstalled[] = "Live"
PluginsInstalled[] = "CustomVariables"
PluginsInstalled[] = "PrivacyManager"
PluginsInstalled[] = "ImageGraph"
PluginsInstalled[] = "Annotations"
PluginsInstalled[] = "MobileMessaging"
PluginsInstalled[] = "Overlay"
PluginsInstalled[] = "SegmentEditor"
PluginsInstalled[] = "Insights"
PluginsInstalled[] = "Morpheus"
PluginsInstalled[] = "Contents"
PluginsInstalled[] = "BulkTracking"
PluginsInstalled[] = "Resolution"
PluginsInstalled[] = "DevicePlugins"
PluginsInstalled[] = "Heartbeat"
PluginsInstalled[] = "Marketplace"
PluginsInstalled[] = "ProfessionalServices"
PluginsInstalled[] = "UserId"
PluginsInstalled[] = "CustomPiwikJs"
PluginsInstalled[] = "Tour"
PluginsInstalled[] = "TagManager"
PluginsInstalled[] = "DBStats"
PluginsInstalled[] = "Provider"
PluginsInstalled[] = "ShortcodeTracker"
PluginsInstalled[] = "BotTracker"
PluginsInstalled[] = "PerformanceAudit"
PluginsInstalled[] = "MarketingCampaignsReporting"
PluginsInstalled[] = "SecurityInfo"
PluginsInstalled[] = "QueuedTracking"
PluginsInstalled[] = "IP2Location"
PluginsInstalled[] = "DevicePixelRatio"
PluginsInstalled[] = "TrackingCodeCustomizer"
PluginsInstalled[] = "FlagCounter"
PluginsInstalled[] = "GoogleTheme"
PluginsInstalled[] = "ReferrersManager"
PluginsInstalled[] = "IntranetGeoIP"
PluginsInstalled[] = "SiteUrlTrackingID"
PluginsInstalled[] = "AjaxOptOut"
PluginsInstalled[] = "TreemapVisualization"
PluginsInstalled[] = "DeviceDetectorCache"
PluginsInstalled[] = "AOM"
PluginsInstalled[] = "CustomDimensions"
PluginsInstalled[] = "ProfileAvatar"
PluginsInstalled[] = "GTheme"
PluginsInstalled[] = "GoogleAnalyticsImporter"
PluginsInstalled[] = "ProtectTrackID"
PluginsInstalled[] = "Webhook"
PluginsInstalled[] = "AbTesting"
PluginsInstalled[] = "ActivityLog"
PluginsInstalled[] = "Cohorts"
PluginsInstalled[] = "CustomReports"
PluginsInstalled[] = "FormAnalytics"
PluginsInstalled[] = "Funnels"
PluginsInstalled[] = "MultiChannelConversionAttribution"
PluginsInstalled[] = "UsersFlow"
PluginsInstalled[] = "SearchEngineKeywordsPerformance"
PluginsInstalled[] = "RollUpReporting"
PluginsInstalled[] = "MediaAnalytics"
PluginsInstalled[] = "HeatmapSessionRecording"
PluginsInstalled[] = "WhiteLabel"
PluginsInstalled[] = "LogViewer"

[QueuedTracking]
notify_queue_threshold_single_queue = 250000

[DeviceDetectorCache]
num_cache_entries = 200000
access_log_path = "/var/log/httpd/access_log"
access_log_regex = "/^(\S+) (\S+) (\S+) (\S+) \[([^:]+):(\d+:\d+:\d+) ([^\]]+)\] \&quot;(\S+) (.*?) (\S+)\&quot; (\S+) (\S+) &quot;([^&quot;]*)&quot; &quot;([^&quot;]*)&quot; (\d+)&#36;/"
regex_match_entry = 14

[CustomReports]
datatable_archiving_maximum_rows_custom_reports = 500
datatable_archiving_maximum_rows_subtable_custom_reports = 500
custom_reports_validate_report_content_all_websites = 1
custom_reports_always_show_unique_visitors = 0
custom_reports_max_execution_time = 0
custom_reports_disabled_dimensions = ""

[Funnels]
funnels_num_max_rows_in_actions = 100
funnels_num_max_rows_in_referrers = 50
funnels_num_max_rows_populate_at_once = 60000

[MultiChannelConversionAttribution]
default_day_prior_to_conversion = 30
available_days_prior_to_conversion = "7,30,60,90"

[UsersFlow]
UsersFlow_num_max_steps = 10
UsersFlow_num_max_rows_in_actions = 100
UsersFlow_num_max_links_per_interaction = 5000

[MediaAnalytics]
media_analytics_exclude_query_parameters = "enablejsapi,player_id"
datatable_archiving_maximum_rows_media = 1000
datatable_archiving_maximum_rows_subtable_media = 1000

[HeatmapSessionRecording]
add_tracking_code_only_when_needed = 1
session_recording_sample_limits = "50,100,250,500,1000,2000,5000"

